// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: champion_stats.sql

package db

import (
	"context"
)

const createChampionStats = `-- name: CreateChampionStats :exec
INSERT INTO champion_stats (data) VALUES ($1)
`

func (q *Queries) CreateChampionStats(ctx context.Context, data []byte) error {
	_, err := q.db.Exec(ctx, createChampionStats, data)
	return err
}

const getLastChampionStats = `-- name: GetLastChampionStats :one
SELECT id, data, created_at FROM champion_stats ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastChampionStats(ctx context.Context) (ChampionStat, error) {
	row := q.db.QueryRow(ctx, getLastChampionStats)
	var i ChampionStat
	err := row.Scan(&i.ID, &i.Data, &i.CreatedAt)
	return i, err
}
