// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: champions.sql

package db

import (
	"context"
)

const createChampion = `-- name: CreateChampion :exec
INSERT INTO champions (api_id, name) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type CreateChampionParams struct {
	ApiID int32
	Name  string
}

func (q *Queries) CreateChampion(ctx context.Context, arg CreateChampionParams) error {
	_, err := q.db.Exec(ctx, createChampion, arg.ApiID, arg.Name)
	return err
}
