// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: matchups.sql

package db

import (
	"context"
)

const createOrUpdateMatchup = `-- name: CreateOrUpdateMatchup :exec
INSERT INTO matchups (champion1_id, champion2_id, wins, games_played) VALUES ($1, $2, $3, 1) ON CONFLICT (champion1_id, champion2_id) DO UPDATE SET wins = matchups.wins + $3, games_played = matchups.games_played + 1 RETURNING id, champion1_id, champion2_id, wins, games_played, created_at
`

type CreateOrUpdateMatchupParams struct {
	Champion1ID int32
	Champion2ID int32
	Wins        int32
}

func (q *Queries) CreateOrUpdateMatchup(ctx context.Context, arg CreateOrUpdateMatchupParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateMatchup, arg.Champion1ID, arg.Champion2ID, arg.Wins)
	return err
}
