// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Champion struct {
	ID        int32
	Name      string
	ApiID     int32
	CreatedAt pgtype.Timestamp
}

type ChampionStat struct {
	ID        int32
	Data      []byte
	CreatedAt pgtype.Timestamp
}

type Match struct {
	ID              int32
	MatchID         string
	GameStart       pgtype.Timestamp
	GameVersion     string
	WinningTeam     string
	Red1ChampionID  int32
	Red2ChampionID  int32
	Red3ChampionID  int32
	Red4ChampionID  int32
	Red5ChampionID  int32
	Blue1ChampionID int32
	Blue2ChampionID int32
	Blue3ChampionID int32
	Blue4ChampionID int32
	Blue5ChampionID int32
	CreatedAt       pgtype.Timestamp
}

type Matchup struct {
	ID          int32
	Champion1ID int32
	Champion2ID int32
	Wins        int32
	GamesPlayed int32
	CreatedAt   pgtype.Timestamp
}

type PlayerSearchLog struct {
	ID         int32
	PlayerID   string
	SearchTime pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

type Synergy struct {
	ID          int32
	Champion1ID int32
	Champion2ID int32
	Wins        int32
	GamesPlayed int32
	CreatedAt   pgtype.Timestamp
}
