// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: synergies.sql

package db

import (
	"context"
)

const createOrUpdateSynergy = `-- name: CreateOrUpdateSynergy :exec
INSERT INTO synergies (champion1_id, champion2_id, wins, games_played) VALUES ($1, $2, $3, 1) ON CONFLICT (champion1_id, champion2_id) DO UPDATE SET wins = synergies.wins + $3, games_played = synergies.games_played + 1 RETURNING id, champion1_id, champion2_id, wins, games_played, created_at
`

type CreateOrUpdateSynergyParams struct {
	Champion1ID int32
	Champion2ID int32
	Wins        int32
}

func (q *Queries) CreateOrUpdateSynergy(ctx context.Context, arg CreateOrUpdateSynergyParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateSynergy, arg.Champion1ID, arg.Champion2ID, arg.Wins)
	return err
}
